env:
  es2021: true
  node: true
  jest: true # fix error not defined Jest functions
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: {
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }], # allows underline in constants for only two files
  import/extensions: 0 # allows import files with extension
}